[remote]
# rsync_path = "rsync://10.1.24.185/labelparty/output"
rsync_path = "/home/vivi"

[leaderboard]
enable = true
host = "10.1.24.185:3000"
githubname = "Vivituhh"

[keybindings]
next = { primary = "Space" }
previous = { primary = "Space", modifiers = ["shift"] }
edit = { primary = "Q" }
zoom = { primary = "E" }
draw = { primary = "B" }
abort = { primary = "Escape" }

select_ball = "Num1"
select_robot = "Num2"
select_goalpost = "Num3"
select_penaltyspot = "Num4"
select_xspot = "X"
select_lspot = "Num5"
select_tspot = "T"
select_jersey = "D"
